### ISSUE TITLE
全部设置好了，运行时经常报以下错误

### ISSUE THREAD

**Issue by gxlqssjf** [liuhll/hero#5]
配置如下：
![image](https://user-images.githubusercontent.com/1277598/105965553-85d03680-60be-11eb-8372-71aa79b0d300.png)
![image](https://user-images.githubusercontent.com/1277598/105965599-9680ac80-60be-11eb-95b2-6fe86f084c90.png)
![image](https://user-images.githubusercontent.com/1277598/105965647-a6988c00-60be-11eb-9c9e-2b9c5caf9e2a.png)
错误如下：
Surging.Hero.FileServiceHost Warning: 0 : [2021-01-27 08:42:47.239 GMT 	WARNING 	ClientCnxn 	!!!Session 0x100012944f101c8 for server {hero.zoo1=>172.23.0.11:2181}, unexpected error, closing socket connection and attempting reconnect] 	
Exc level 0: org.apache.zookeeper.ClientCnxn+SessionExpiredException: Unable to reconnect to ZooKeeper service, session 0x100012944f101c8 has expired
   at org.apache.zookeeper.ClientCnxn.onConnected(Int32 _negotiatedSessionTimeout, Int64 _sessionId, Byte[] _sessionPasswd, Boolean isRO)
   at org.apache.zookeeper.ClientCnxnSocket.readConnectResult()
   at org.apache.zookeeper.ClientCnxnSocketNIO.doIO()
   at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(Int32 waitTimeOut)
   at org.apache.zookeeper.ClientCnxn.startSendTask()
![image](https://user-images.githubusercontent.com/1277598/105965750-c4fe8780-60be-11eb-84d7-6ccf77112652.png)
此异常最初是在此调用堆栈中引发的: 
    Rabbit.Zookeeper.Implementation.ZookeeperClient.RetryUntilConnected<T>(System.Func<System.Threading.Tasks.Task<T>>)
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
    System.Runtime.CompilerServices.TaskAwaiter<TResult>.GetResult()
    Rabbit.Zookeeper.Implementation.ZookeeperClient.ExistsAsync(string)
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
    System.Runtime.CompilerServices.TaskAwaiter<TResult>.GetResult()
    ...
    [调用堆栈已截断]

**Comment by liuhll** [comment]
检查服务中心配置是否正确

**Comment by gxlqssjf** [comment]
你说的服务中心配置指的是？？我检查了全部配置，都OK的,请指教
